- name: copying files to ssh
  copy: src={{ item }} dest=/home/{{ user }}/.ssh/ owner={{ user }} group={{ user }} mode=0644
  with_items:
    - config
    - id_rsa.pub
    - known_hosts

- name: copying files to ssh
  copy: src={{ item }} dest=/home/{{ user }}/.ssh/ owner={{ user }} group={{ user }} mode=0600
  with_items:
    - id_rsa
    - ubuntu.id_rsa
    - vagrant.id_rsa

- name: downloading dotfiles repo
  tags: dotfiles
  get_url: url=https://github.com/lerovitch/dotfiles/archive/master.zip dest=/home/{{ user }}/git owner={{ user }} group={{ user }} 

- name: unarchiving dotfiles repo
  tags: dotfiles
  unarchive: src=/home/{{ user }}/git/dotfiles-master.zip dest=/home/{{ user }}/git copy=no

- name: stat dotfiles
  tags: dotfiles
  stat: path=/home/{{ user }}/git/dotfiles-master
  register: dotfiles_stat

- name: Move dotfiles 
  tags: dotfiles
  command: mv /home/{{ user }}/git/dotfiles-master /home/{{user}}/git/dotfiles
  when: dotfiles_stat.stat.exists
  ignore_errors: yes

- name: Assures /home/{{ user }}/git/dotfiles with  proper permissions
  tags: dotfiles
  file: path=/home/{{ user }}/git/dotfiles state=directory owner={{ user }} group={{ user }} recurse=yes

- name: Assures /home/{{ user }}/.local/share/fonts dir exists
  tags: ide
  file: path=/home/{{ user }}/.local/share/fonts state=directory

- name: copying font file
  tags: ide
  copy: src=/home/{{ user }}/git/dotfiles/fonts/Monaco.otf dest=/home/{{ user }}/.local/share/fonts/Monaco.otf owner={{ user }} group={{ user }}

- name: configuring terminator (creating dir)
  tags: ide
  file: path=/home/{{ user }}/.config/terminator state=directory owner={{ user }} group={{ user }}

- name: configuring terminator (symbolic link)
  tags: ide
  file: src=/home/{{ user }}/git/dotfiles/ubuntu/terminator/config dest=/home/{{ user }}/.config/terminator/config state=link owner={{ user }} group={{ user }}
          
- name: configuring bash profile
  tags: ide
  file: src=/home/{{ user }}/git/dotfiles/bash/bash_profile dest=/home/{{ user }}/.bashrc state=link force=yes owner={{ user }} group={{ user }}

- name: update font cache
  tags: ide
  sudo: yes
  command: fc-cache -f -v
