- name: create user
  user: name={{ user }} shell=/bin/bash remove=yes state=present password=$6$mUSuXNobrXc6R2oA$QE3co9llnxpcEM9a1H2wxc2TWoj3vIum3qpJovkJWrJkyN4DVGaPzgyWZJscZbUsClAMmIg61PH5uQkCf0wGX/
  tags:
    - developer

- name: add developer to sudoer
  sudo: yes
  copy: src=sudoers dest=/etc/sudoers


#- name: add getdeb key
#  apt_key: url=http://archive.getdebnet/getdeb-archive.key state=present
#
#- name: add getdeb repo 
#  apt_repository: repo='deb http://archive.getdeb.net/ubuntu trusty-getdeb apps' state=present

#- name: install desktop
#  apt: name=ubuntu-desktop state=present install_recommends=no
  
- name: adding packages
  action: apt pkg={{item}} state=installed
  with_items:
  - terminator
  - git      
  - git-svn
  - vim-gnome
  - subversion
  - ctags
  - ack-grep
  - nscd 
 

- include: skyscanner.yml

