- name: create user
  user: name={{ user }} shell=/bin/bash remove=yes state=present password=$6$mUSuXNobrXc6R2oA$QE3co9llnxpcEM9a1H2wxc2TWoj3vIum3qpJovkJWrJkyN4DVGaPzgyWZJscZbUsClAMmIg61PH5uQkCf0wGX/
  tags:
    - developer

- name: add developer to sudoer
  sudo: yes
  copy: src=sudoers dest=/etc/sudoers


- name: add postgresql key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: add postgresql repo 
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

  
- name: adding packages
  action: apt pkg={{item}} state=installed
  with_items:
  - terminator
  - curl
  - git      
  - git-svn
  - vim-gtk
  - subversion
  - ctags
  - ack-grep
  - default-jdk
  - libreadline-dev
  - libssl-dev
  - zlib1g-dev
  - sqlite3
  - python-dev
  - postgresql-8.4
  - libpq-dev
  - python-pip
  
- name: disable GSSAPIAuth
  lineinfile: dest=/etc/ssh/sshd_config regexp=".*{{ item }}.*" state=absent
  tags: ssh
  with_items:
    - GSSAPIAuth
    - GSSAPIDelegate
  
- name: disable GSSAPIAuth
  lineinfile: dest=/etc/ssh/ssh_config regexp=".*{{ item }}.*" state=absent
  tags: ssh
  with_items:
    - GSSAPIAuth
    - GSSAPIDelegate
  
- name: get pycharm
  get_url: url=http://download.jetbrains.com/python/pycharm-professional-3.4.1.tar.gz dest=/home/{{ user }}/pycharm-professional-3.4.1.tar.gz mode=0440 owner={{user}} group={{user}}
  
- name: download pyenv
  tags: pyenv
  get_url: url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer dest=/tmp/pyenv-installer  owner={{user}} group={{user}}

- name: install pyenv
  tags: pyenv
  command: sh /tmp/pyenv-installer

- name: copying files to ssh
  copy: src={{ item }} dest=/home/{{ user }}/.ssh/ owner={{ user }} group={{ user }} mode=0644
  with_items:
    - config
    - id_rsa.pub
    - known_hosts

- name: copying files to ssh
  copy: src={{ item }} dest=/home/{{ user }}/.ssh/ owner={{ user }} group={{ user }} mode=0600
  with_items:
    - id_rsa
    - ubuntu.id_rsa
    - vagrant.id_rsa

- name: cloning dotfiles repo
  git: repo=git@github.com:lerovitch/dotfiles.git dest=/home/{{ user }}/git/dotfiles
   
- name: Assures /home/{{ user }}/.local/share/fonts dir exists
  tags: ide
  file: path=/home/{{ user }}/.local/share/fonts state=directory

- name: copying font file
  tags: ide
  copy: src=/home/{{ user }}/git/dotfiles/fonts/Monaco.otf dest=/home/{{ user }}/.local/share/fonts/Monaco.otf owner={{ user }} group={{ user }}

- name: configuring terminator (creating dir)
  tags: ide
  file: path=/home/{{ user }}/.config/terminator state=directory

- name: configuring terminator (symbolic link)
  tags: ide
  file: src=/home/{{ user }}/git/dotfiles/ubuntu/terminator/config dest=/home/{{ user }}/.config/terminator/config state=link
          
- name: configuring bash profile
  tags: ide
  file: src=/home/{{ user }}/git/dotfiles/bash/bash_profile dest=/home/{{ user }}/.bashrc state=link force=yes

  
- name: update font cache
  tags: ide
  sudo: yes
  command: fc-cache -f -v
  







 
- include: skyscanner.yml

