---

- name: copying files to etc
  sudo: yes
  tags: network
  copy: src={{ item }} dest=/etc
  with_items:
     - hosts
     - nsswitch.conf

- name: copying interfaces
  sudo: yes
  tags: network
  copy: src=interfaces  dest=/etc/network

- name: regenerate resolv.conf file
  sudo: yes
  tags: network
  command: resolvconf -u
